# #!/bin/bash
# # -----------------------------------------------------------
# # import_s3_buckets.sh
# #
# # Discovers manually created S3 buckets via AWS CLI and
# # auto-generates Terraform import + resource blocks.
# #
# # Usage:
# #   chmod +x import_s3_buckets.sh
# #   ./import_s3_buckets.sh                         # all buckets
# #   ./import_s3_buckets.sh --region eu-west-2      # specific region
# #   ./import_s3_buckets.sh --tag ManagedBy=manual  # filter by tag
# # -----------------------------------------------------------

# set -e

# REGION="${AWS_DEFAULT_REGION:-eu-west-2}"
# TAG_FILTER=""
# OUTPUT_FILE="imported_buckets.tf"

# # --- Parse arguments ---
# while [[ "$#" -gt 0 ]]; do
#   case $1 in
#     --region) REGION="$2"; shift ;;
#     --tag)    TAG_FILTER="$2"; shift ;;
#     *) echo "Unknown param: $1"; exit 1 ;;
#   esac
#   shift
# done

# echo "=================================================="
# echo " Terraform S3 Bucket Import Generator"
# echo " Region : $REGION"
# echo " Tag    : ${TAG_FILTER:-<all buckets>}"
# echo "=================================================="
# echo ""

# # --- Step 1: List all S3 buckets ---
# echo ">> Fetching all S3 buckets in account..."
# ALL_BUCKETS=$(aws s3api list-buckets \
#   --query "Buckets[*].Name" \
#   --output text)

# if [[ -z "$ALL_BUCKETS" ]]; then
#   echo "No buckets found."
#   exit 0
# fi

# # --- Step 2: Filter buckets by region and optional tag ---
# MATCHED_BUCKETS=()

# for BUCKET in $ALL_BUCKETS; do
#   # Check bucket region
#   BUCKET_REGION=$(aws s3api get-bucket-location \
#     --bucket "$BUCKET" \
#     --query "LocationConstraint" \
#     --output text 2>/dev/null || echo "unknown")

#   # us-east-1 returns "None" from AWS CLI
#   [[ "$BUCKET_REGION" == "None" ]] && BUCKET_REGION="us-east-1"

#   if [[ "$BUCKET_REGION" != "$REGION" ]]; then
#     continue
#   fi

#   # Optional tag filter
#   if [[ -n "$TAG_FILTER" ]]; then
#     TAG_KEY="${TAG_FILTER%%=*}"
#     TAG_VAL="${TAG_FILTER##*=}"
#     MATCH=$(aws s3api get-bucket-tagging \
#       --bucket "$BUCKET" \
#       --query "TagSet[?Key=='${TAG_KEY}' && Value=='${TAG_VAL}'].Value" \
#       --output text 2>/dev/null || echo "")
#     [[ -z "$MATCH" ]] && continue
#   fi

#   MATCHED_BUCKETS+=("$BUCKET")
# done

# # --- Step 3: Show results ---
# echo ""
# echo ">> Found ${#MATCHED_BUCKETS[@]} bucket(s) in region '$REGION':"
# echo ""
# for BUCKET in "${MATCHED_BUCKETS[@]}"; do
#   echo "   - $BUCKET"
# done

# if [[ "${#MATCHED_BUCKETS[@]}" -eq 0 ]]; then
#   echo "   No matching buckets found."
#   exit 0
# fi

# # --- Step 4: Generate Terraform import + resource blocks ---
# echo ""
# echo ">> Generating Terraform config -> $OUTPUT_FILE"
# echo ""

# cat > "$OUTPUT_FILE" <<EOF
# # -----------------------------------------------------------
# # Auto-generated by import_s3_buckets.sh
# # Region  : $REGION
# # Date    : $(date +"%Y-%m-%d %H:%M:%S")
# # Buckets : ${#MATCHED_BUCKETS[@]}
# # -----------------------------------------------------------

# EOF

# for BUCKET in "${MATCHED_BUCKETS[@]}"; do
#   # Sanitize bucket name for Terraform resource label
#   LABEL=$(echo "$BUCKET" | tr '-' '_' | tr '.' '_')

#   cat >> "$OUTPUT_FILE" <<EOF
# import {
#   to = aws_s3_bucket.${LABEL}
#   id = "${BUCKET}"
# }

# resource "aws_s3_bucket" "${LABEL}" {
#   bucket = "${BUCKET}"

#   tags = {
#     ManagedBy = "terraform"
#   }
# }

# EOF
#   echo "   + import block generated for: $BUCKET"
# done

# echo ""
# echo "=================================================="
# echo " Done! Next steps:"
# echo ""
# echo "   1. Review the generated file:"
# echo "      cat $OUTPUT_FILE"
# echo ""
# echo "   2. Preview the import:"
# echo "      terraform plan"
# echo ""
# echo "   3. Apply the import:"
# echo "      terraform apply"
# echo "=================================================="
